name: medsam
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.11.12
  - comm=0.2.3
  - debugpy=1.8.16
  - expat=2.7.1
  - importlib-metadata=8.7.0
  - ipykernel=7.1.0
  - jupyter_client=8.6.3
  - jupyter_core=5.9.1
  - ld_impl_linux-64=2.44
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libnsl=2.0.0
  - libsodium=1.0.20
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - openssl=3.0.18
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - python=3.10.19
  - python-dateutil=2.9.0.post0
  - python_abi=3.10
  - pyzmq=27.1.0
  - readline=8.3
  - setuptools=80.9.0
  - sqlite=3.50.2
  - stack_data=0.6.3
  - tk=8.6.15
  - tornado=6.5.1
  - traitlets=5.14.3
  - typing_extensions=4.15.0
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - pip:
      - accelerate==0.21.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.9.5
      - aiosignal==1.3.1
      - albumentations==0.3.2
      - annotated-doc==0.0.3
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.11.0
      - anykeystore==0.2
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.4.0
      - asn1crypto==1.5.1
      - astor==0.8.1
      - asttokens==2.4.1
      - async-lru==2.0.5
      - async-timeout==4.0.3
      - attrs==25.4.0
      - av==15.1.0
      - azure-core==1.36.0
      - azure-identity==1.25.1
      - babel==2.17.0
      - beautifulsoup4==4.14.2
      - bidict==0.23.1
      - blake3==1.0.8
      - bleach==6.3.0
      - blessed==1.20.0
      - boto3==1.34.113
      - botocore==1.34.113
      - braceexpand==0.1.7
      - cachetools==5.3.3
      - cbor2==5.7.1
      - certifi==2024.2.2
      - cffi==1.16.0
      - chardet==5.2.0
      - charset-normalizer==3.3.2
      - click==8.1.7
      - clip==0.2.0
      - clip-openai==1.0.post20230121
      - cloudpickle==3.1.1
      - cmake==3.29.3
      - compressed-tensors==0.11.0
      - contourpy==1.3.2
      - cramjam==2.8.3
      - crcmod==1.7
      - cryptacular==1.6.2
      - cryptography==39.0.2
      - cupy-cuda12x==13.6.0
      - cycler==0.12.1
      - datasets==2.2.1
      - decorator==5.1.1
      - decord==0.6.0
      - deepspeed==0.14.2
      - defusedxml==0.7.1
      - deprecated==1.2.14
      - depyf==0.19.0
      - descartes==1.1.0
      - diffusers==0.30.1
      - dill==0.3.8
      - diskcache==5.6.3
      - distlib==0.3.8
      - distro==1.9.0
      - distro-info==1.0
      - dnspython==2.6.1
      - docker-pycreds==0.4.0
      - docstring-parser==0.16
      - ecdsa==0.19.0
      - einops==0.6.0
      - email-validator==2.3.0
      - exceptiongroup==1.2.1
      - executing==2.0.1
      - fairscale==0.4.13
      - fastapi==0.120.4
      - fastapi-cli==0.0.14
      # - fastapi-cloud-cli==0.3.1
      - fastjsonschema==2.21.2
      - fastparquet==2024.5.0
      - fastrlock==0.8.3
      - ffmpegcv==0.3.13
      - filelock==3.14.0
      - fire==0.6.0
      # - flash-attn==2.5.7
      - fonttools==4.51.0
      - fqdn==1.5.1
      - frozendict==2.4.6
      - frozenlist==1.4.1
      - fsspec==2023.6.0
      - ftfy==6.2.0
      - gdown==5.2.0
      - gguf==0.17.1
      - gitdb==4.0.11
      - gitpython==3.1.43
      - google-auth==2.41.1
      - google-genai==1.39.1
      - gpustat==1.1.1
      - greenlet==3.0.3
      - grpcio==1.64.0
      - h11==0.16.0
      - hf-xet==1.1.10
      - hjson==3.1.0
      - httpcore==1.0.9
      - httptools==0.7.1
      - httpx==0.28.1
      - huggingface-hub==0.23.2
      - hupper==1.12.1
      - idna==3.7
      - imageio==2.34.1
      - imgaug==0.2.6
      - importlib-resources==6.5.2
      - iniconfig==2.0.0
      - interegular==0.3.3
      - ipaddress==1.0.23
      - ipdb==0.13.13
      - ipympl==0.9.8
      - ipython==8.18.1
      - ipywidgets==8.1.8
      - isoduration==20.11.0
      - jaxtyping==0.2.28
      - jedi==0.19.1
      - jinja2==3.1.4
      - jiter==0.11.0
      - jmespath==1.0.1
      - joblib==1.4.2
      - json5==0.12.1
      - jsonargparse==4.14.1
      - jsonlines==4.0.0
      - jsonpointer==3.0.0
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.5.1
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.28.0
      - jupyterlab-widgets==3.0.16
      - kiwisolver==1.4.5
      - kornia==0.7.2
      - kornia-rs==0.1.3
      - lark==1.2.2
      - lazy-loader==0.4
      - lightning==2.2.3
      - lightning-utilities==0.11.2
      - lit==18.1.6
      # - llava==1.7.0.dev0
      - llguidance==0.7.30
      - llvmlite==0.44.0
      - lm-format-enforcer==0.11.3
      - markdown-it-py==4.0.0
      - markupsafe==2.1.5
      - mathruler==0.1.0
      - matplotlib==3.5.3
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      # - medevalkit==0.1.0
      # - medsam==0.1.0
      - miscreant==0.3.0
      - mistral-common==1.8.5
      - mistune==3.1.4
      - mpmath==1.3.0
      - msal==1.34.0
      - msal-extensions==1.3.1
      - msgpack==1.0.8
      - msgspec==0.19.0
      - multidict==6.0.5
      - multiprocess==0.70.16
      - natsort==8.4.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - networkx==3.2.1
      - nibabel==5.3.3
      - ninja==1.11.1.1
      - nltk==3.9.1
      - notebook-shim==0.2.4
      - numba==0.61.2
      - numpy==1.24.4
      - nuscenes-devkit==1.1.11
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-ml-py==13.580.82
      - nvidia-nccl-cu12==2.19.3
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvtx-cu12==12.1.105
      - oauthlib==3.2.2
      - omegaconf==2.3.0
      - open-clip-torch==2.24.0
      - openai==2.6.1
      - openai-clip==1.0.1
      - openai-harmony==0.0.4
      - opencv-python==4.9.0.80
      - opencv-python-headless==3.4.18.65
      - outlines-core==0.2.11
      - overrides==7.7.0
      - packaging==22.0
      - pandas==1.5.3
      - pandocfilters==1.5.1
      - parquet==1.3.1
      - parso==0.8.4
      - partial-json-parser==0.2.1.1.post6
      - pastedeploy==3.1.0
      - pathlib2==2.3.7.post1
      - pathtools==0.1.2
      - pbkdf2==1.3
      - pillow==10.3.0
      - pip==25.3
      - plaster==1.1.2
      - plaster-pastedeploy==1.0.1
      - platformdirs==4.2.2
      - plotly==5.22.0
      - pluggy==1.5.0
      - ply==3.11
      - prometheus-client==0.23.1
      - prometheus-fastapi-instrumentator==7.1.0
      - promise==2.3
      - prompt-toolkit==3.0.43
      - propcache==0.3.2
      - protobuf==3.20.3
      - psutil==5.9.8
      - pure-eval==0.2.2
      - py==1.11.0
      - py-cpuinfo==9.0.0
      - py-spy==0.3.14
      - pyarrow==11.0.0
      - pyarrow-hotfix==0.6
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.2
      - pybase64==1.4.2
      - pycocotools==2.0.7
      - pycountry==24.6.1
      - pycparser==2.22
      - pycryptodomex==3.20.0
      - pycurl==7.43.0.6
      - pydantic==2.12.5
      - pydantic-core==2.41.5
      - pydantic-extra-types==2.10.6
      - pydash==8.0.5
      - pygments==2.18.0
      - pyjwt==2.8.0
      - pylatexenc==2.10
      - pynvml==11.5.0
      - pyope==0.2.2
      - pyopenssl==23.2.0
      - pyparsing==3.1.2
      - pyquaternion==0.9.9
      - pyramid==2.0.2
      - pyramid-mailer==0.15.1
      - pysocks==1.7.1
      - pytest==6.2.5
      - python-consul==1.1.0
      - python-dotenv==1.2.1
      - python-engineio==4.9.1
      - python-etcd==0.4.5
      - python-jose==3.3.0
      - python-json-logger==4.0.0
      - python-multipart==0.0.20
      - python-socketio==5.11.2
      - python3-openid==3.2.0
      - pytorch-extension==0.2
      - pytorch-lightning==2.2.3
      - pytz==2024.1
      - pyyaml==6.0.1
      - qwen-vl-utils==0.0.14
      - ray==2.51.1
      - referencing==0.37.0
      - regex==2024.5.15
      - repoze-sendmail==4.4.1
      - requests==2.31.0
      - requests-oauthlib==2.0.0
      - responses==0.18.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rich==14.2.0
      - rich-toolkit==0.15.1
      - rignore==0.7.3
      - rouge==1.0.1
      - rpds-py==0.28.0
      - rsa==4.9
      - s3transfer==0.10.1
      - safetensors==0.4.3
      - schedule==1.2.2
      - scikit-image==0.22.0
      - scikit-learn==1.5.0
      - scipy==1.13.1
      - send2trash==1.8.3
      - sentencepiece==0.2.0
      - sentry-sdk==2.3.1
      - setproctitle==1.3.3
      - shapely==1.8.5.post1
      - shellingham==1.5.4
      - shortuuid==1.0.13
      # - show-o==0.1.0
      - simple-websocket==1.0.0
      - simpleitk==2.5.3
      - six==1.16.0
      - smmap==5.0.1
      - sniffio==1.3.1
      - soundfile==0.13.1
      - soupsieve==2.8
      - soxr==1.0.0
      - sqlalchemy==2.0.30
      - starlette==0.49.3
      - sympy==1.12
      - taming-transformers-rom1504==0.0.6
      - tenacity==8.3.0
      - tensorboardx==2.6.2.2
      - termcolor==2.4.0
      - terminado==0.18.1
      - threadpoolctl==3.5.0
      - thriftpy2==0.5.0
      - tifffile==2024.5.22
      - tiktoken==0.12.0
      - timm==1.0.3
      - tinycss2==1.4.0
      - tokenizers==0.19.1
      - toml==0.10.2
      - tomli==2.0.1
      - torch==2.2.1
      - torch-fidelity==0.3.0
      - torchaudio==2.8.0
      - torchmetrics==1.4.0.post0
      - torchvision==0.17.1
      - tox==3.28.0
      - tqdm==4.66.4
      - transaction==4.0
      - transformers==4.41.1
      - translationstring==1.4
      - triton==2.2.0
      - typeguard==2.13.3
      - typer==0.20.0
      - typing-inspection==0.4.2
      - tzdata==2024.1
      - uri-template==1.3.0
      - urllib3==1.26.18
      - uvicorn==0.38.0
      - uvloop==0.22.1
      - velruse==1.1.1
      - venusian==3.1.0
      - virtualenv==20.26.2
      - vllm==0.11.0
      - vlm==0.0.1
      - wadler-lindig==0.1.7
      - wandb==0.17.0
      - watchdog==4.0.1
      - watchfiles==1.1.1
      - wcwidth==0.2.13
      - webcolors==25.10.0
      - webdataset==0.2.86
      - webencodings==0.5.1
      - webob==1.8.7
      - websocket-client==1.8.0
      - websockets==15.0.1
      - widgetsnbextension==4.0.15
      - wrapt==1.16.0
      - wsproto==1.2.0
      - wtforms==3.1.2
      - wtforms-recaptcha==0.3.2
      - xformers==0.0.25
      - xgrammar==0.1.25
      - xxhash==3.4.1
      - yarl==1.9.4
      - zope-deprecation==5.0
      - zope-interface==6.4.post2
      - zope-sqlalchemy==3.1
prefix: /home/t-qimhuang/miniconda3/envs/medsam
