azstorage:
  type: block # or block if you're using traditional blob
  account-name: singaporeteamstorage
  container: shared ## no need to change since we only can use this container and blob always mounts an entire container. 
  endpoint: https://singaporeteamstorage.blob.core.windows.net
  mode: azcli
